package com.myspace.surveillanceproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AccountableParty implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("fullName")
	private java.lang.String fullName;
	@org.kie.api.definition.type.Label("phoneNumber")
	private java.lang.String phoneNumber;
	@org.kie.api.definition.type.Label("email")
	private java.lang.String email;

	@org.kie.api.definition.type.Label(value = "role")
	private java.lang.String role;

	public AccountableParty() {
	}

	public java.lang.String getFullName() {
		return this.fullName;
	}

	public void setFullName(java.lang.String fullName) {
		this.fullName = fullName;
	}

	public java.lang.String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(java.lang.String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getRole() {
		return this.role;
	}

	public void setRole(java.lang.String role) {
		this.role = role;
	}

	public AccountableParty(java.lang.String fullName,
			java.lang.String phoneNumber, java.lang.String email,
			java.lang.String role) {
		this.fullName = fullName;
		this.phoneNumber = phoneNumber;
		this.email = email;
		this.role = role;
	}

}