package com.myspace.surveillanceproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CheckListInstance implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "checkList")
	private java.lang.String checkList;

	public CheckListInstance() {
	}

	public java.lang.String getCheckList() {
		return this.checkList;
	}

	public void setCheckList(java.lang.String checkList) {
		this.checkList = checkList;
	}

	public CheckListInstance(java.lang.String checkList) {
		this.checkList = checkList;
	}

}