package com.myspace.surveillanceproject;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CommonInspectionObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("subject")
	private java.lang.String subject;
	@org.kie.api.definition.type.Label("subjectSubsidiary")
	private java.lang.String subjectSubsidiary;
	@org.kie.api.definition.type.Label("institution")
	private java.lang.String institution;
	@org.kie.api.definition.type.Label("sector")
	private java.lang.String sector;
	@org.kie.api.definition.type.Label("createdAt")
	private Date createdAt;
	@org.kie.api.definition.type.Label("assignedTo")
	private java.lang.String assignedTo;

	@org.kie.api.definition.type.Label("processInstanceId")
	private java.lang.Long processInstanceId;

	@org.kie.api.definition.type.Label(value = "createdBy")
	private java.lang.String createdBy;

	public CommonInspectionObject() {
	}

	public java.lang.String getSubject() {
		return this.subject;
	}

	public void setSubject(java.lang.String subject) {
		this.subject = subject;
	}

	public java.lang.String getSubjectSubsidiary() {
		return this.subjectSubsidiary;
	}

	public void setSubjectSubsidiary(java.lang.String subjectSubsidiary) {
		this.subjectSubsidiary = subjectSubsidiary;
	}

	public java.lang.String getInstitution() {
		return this.institution;
	}

	public void setInstitution(java.lang.String institution) {
		this.institution = institution;
	}

	public java.lang.String getSector() {
		return this.sector;
	}

	public void setSector(java.lang.String sector) {
		this.sector = sector;
	}

	public java.lang.String getAssignedTo() {
		return this.assignedTo;
	}

	public void setAssignedTo(java.lang.String assignedTo) {
		this.assignedTo = assignedTo;
	}

	public java.util.Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(java.util.Date createdAt) {
		this.createdAt = createdAt;
	}

	public java.lang.Long getProcessInstanceId() {
		return this.processInstanceId;
	}

	public void setProcessInstanceId(java.lang.Long processInstanceId) {
		this.processInstanceId = processInstanceId;
	}

	public java.lang.String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(java.lang.String createdBy) {
		this.createdBy = createdBy;
	}

	public CommonInspectionObject(java.lang.String subject,
			java.lang.String subjectSubsidiary, java.lang.String institution,
			java.lang.String sector, java.util.Date createdAt,
			java.lang.String assignedTo, java.lang.Long processInstanceId,
			java.lang.String createdBy) {
		this.subject = subject;
		this.subjectSubsidiary = subjectSubsidiary;
		this.institution = institution;
		this.sector = sector;
		this.createdAt = createdAt;
		this.assignedTo = assignedTo;
		this.processInstanceId = processInstanceId;
		this.createdBy = createdBy;
	}

}