package com.myspace.surveillanceproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ConclusionMeasures implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("repercussion")
	private com.myspace.surveillanceproject.Repercussion repercussion;
	@org.kie.api.definition.type.Label("scheduleControl")
	private java.lang.Boolean scheduleControl;

	public ConclusionMeasures() {
	}

	public com.myspace.surveillanceproject.Repercussion getRepercussion() {
		return this.repercussion;
	}

	public void setRepercussion(
			com.myspace.surveillanceproject.Repercussion repercussion) {
		this.repercussion = repercussion;
	}

	public java.lang.Boolean getScheduleControl() {
		return this.scheduleControl;
	}

	public void setScheduleControl(java.lang.Boolean scheduleControl) {
		this.scheduleControl = scheduleControl;
	}

	public ConclusionMeasures(
			com.myspace.surveillanceproject.Repercussion repercussion,
			java.lang.Boolean scheduleControl) {
		this.repercussion = repercussion;
		this.scheduleControl = scheduleControl;
	}

}