package com.myspace.surveillanceproject;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InspectionCheck implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("type")
	private java.lang.String type;
	@org.kie.api.definition.type.Label("knownSubject")
	private String knownSubject;
	@org.kie.api.definition.type.Label("checkDate")
	private Date checkDate;
	@org.kie.api.definition.type.Label("description")
	private java.lang.String description;
	@org.kie.api.definition.type.Label("inspectionScope")
	private java.lang.String inspectionScope;
	@org.kie.api.definition.type.Label("common")
	private com.myspace.surveillanceproject.CommonInspectionObject common;

	@org.kie.api.definition.type.Label("laws")
	private java.util.List<com.myspace.surveillanceproject.LawInstance> laws;

	@org.kie.api.definition.type.Label("id")
	private java.lang.String id;

	@org.kie.api.definition.type.Label("announcedSupervisionDate")
	private java.util.Date announcedSupervisionDate;

	@org.kie.api.definition.type.Label("announcedSupervision")
	private java.lang.Boolean announcedSupervision;

	@org.kie.api.definition.type.Label(value = "documents")
	private java.util.List<com.myspace.surveillanceproject.Documents> documents;

	public InspectionCheck() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getInspectionScope() {
		return this.inspectionScope;
	}

	public void setInspectionScope(java.lang.String inspectionScope) {
		this.inspectionScope = inspectionScope;
	}

	public com.myspace.surveillanceproject.CommonInspectionObject getCommon() {
		return this.common;
	}

	public void setCommon(
			com.myspace.surveillanceproject.CommonInspectionObject common) {
		this.common = common;
	}

	public java.util.List<com.myspace.surveillanceproject.LawInstance> getLaws() {
		return this.laws;
	}

	public void setLaws(
			java.util.List<com.myspace.surveillanceproject.LawInstance> laws) {
		this.laws = laws;
	}

	public java.util.Date getCheckDate() {
		return this.checkDate;
	}

	public void setCheckDate(java.util.Date checkDate) {
		this.checkDate = checkDate;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.util.Date getAnnouncedSupervisionDate() {
		return this.announcedSupervisionDate;
	}

	public void setAnnouncedSupervisionDate(
			java.util.Date announcedSupervisionDate) {
		this.announcedSupervisionDate = announcedSupervisionDate;
	}

	public java.lang.Boolean getAnnouncedSupervision() {
		return this.announcedSupervision;
	}

	public void setAnnouncedSupervision(java.lang.Boolean announcedSupervision) {
		this.announcedSupervision = announcedSupervision;
	}

	public java.lang.String getKnownSubject() {
		return this.knownSubject;
	}

	public void setKnownSubject(java.lang.String knownSubject) {
		this.knownSubject = knownSubject;
	}

	public java.util.List<com.myspace.surveillanceproject.Documents> getDocuments() {
		return this.documents;
	}

	public void setDocuments(
			java.util.List<com.myspace.surveillanceproject.Documents> documents) {
		this.documents = documents;
	}

	public InspectionCheck(java.lang.String type,
			java.lang.String knownSubject, java.util.Date checkDate,
			java.lang.String description, java.lang.String inspectionScope,
			com.myspace.surveillanceproject.CommonInspectionObject common,
			java.util.List<com.myspace.surveillanceproject.LawInstance> laws,
			java.lang.String id, java.util.Date announcedSupervisionDate,
			java.lang.Boolean announcedSupervision,
			java.util.List<com.myspace.surveillanceproject.Documents> documents) {
		this.type = type;
		this.knownSubject = knownSubject;
		this.checkDate = checkDate;
		this.description = description;
		this.inspectionScope = inspectionScope;
		this.common = common;
		this.laws = laws;
		this.id = id;
		this.announcedSupervisionDate = announcedSupervisionDate;
		this.announcedSupervision = announcedSupervision;
		this.documents = documents;
	}

}