package com.myspace.surveillanceproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InspectionCase implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("common")
	private com.myspace.surveillanceproject.CommonInspectionObject common;
	@org.kie.api.definition.type.Label("name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("description")
	private java.lang.String description;
	@org.kie.api.definition.type.Label("archiveNumber")
	private java.lang.String archiveNumber;

	@org.kie.api.definition.type.Label(value = "id")
	private java.lang.String id;

	public InspectionCase() {
	}

	public com.myspace.surveillanceproject.CommonInspectionObject getCommon() {
		return this.common;
	}

	public void setCommon(
			com.myspace.surveillanceproject.CommonInspectionObject common) {
		this.common = common;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getArchiveNumber() {
		return this.archiveNumber;
	}

	public void setArchiveNumber(java.lang.String archiveNumber) {
		this.archiveNumber = archiveNumber;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public InspectionCase(
			com.myspace.surveillanceproject.CommonInspectionObject common,
			java.lang.String name, java.lang.String description,
			java.lang.String archiveNumber, java.lang.String id) {
		this.common = common;
		this.name = name;
		this.description = description;
		this.archiveNumber = archiveNumber;
		this.id = id;
	}

}