package com.myspace.surveillanceproject;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InspectionWorkOrder implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("workOrderDate")
	private Date workOrderDate;
	@org.kie.api.definition.type.Label("inspectionCheckDate")
	private Date inspectionCheckDate;
	@org.kie.api.definition.type.Label("archiveNumber")
	private java.lang.String archiveNumber;
	@org.kie.api.definition.type.Label("inspectionScope")
	private java.lang.String inspectionScope;

	@org.kie.api.definition.type.Label("laws")
	private java.util.List<com.myspace.surveillanceproject.LawInstance> laws;

	@org.kie.api.definition.type.Label("common")
	private com.myspace.surveillanceproject.CommonInspectionObject common;

	@org.kie.api.definition.type.Label("id")
	private java.lang.String id;

	@org.kie.api.definition.type.Label("type")
	private java.lang.String type;

	@org.kie.api.definition.type.Label("archiveDate")
	private java.util.Date archiveDate;

	@org.kie.api.definition.type.Label("itgMonthlyPlanId")
	private java.lang.String itgMonthlyPlanId;

	@org.kie.api.definition.type.Label("inspectionWorkOrderReasonId")
	private java.lang.String inspectionWorkOrderReasonId;

	@org.kie.api.definition.type.Label("documents")
	private java.util.List<com.myspace.surveillanceproject.Documents> documents;

	@org.kie.api.definition.type.Label("institutionList")
	private java.util.List<java.lang.String> institutionList;

	@org.kie.api.definition.type.Label(value = "complexityFactor")
	private java.lang.String complexityFactor;

	public InspectionWorkOrder() {
	}

	public java.lang.String getArchiveNumber() {
		return this.archiveNumber;
	}

	public void setArchiveNumber(java.lang.String archiveNumber) {
		this.archiveNumber = archiveNumber;
	}

	public java.lang.String getInspectionScope() {
		return this.inspectionScope;
	}

	public void setInspectionScope(java.lang.String inspectionScope) {
		this.inspectionScope = inspectionScope;
	}

	public java.util.List<com.myspace.surveillanceproject.LawInstance> getLaws() {
		return this.laws;
	}

	public void setLaws(
			java.util.List<com.myspace.surveillanceproject.LawInstance> laws) {
		this.laws = laws;
	}

	public com.myspace.surveillanceproject.CommonInspectionObject getCommon() {
		return this.common;
	}

	public void setCommon(
			com.myspace.surveillanceproject.CommonInspectionObject common) {
		this.common = common;
	}

	public java.util.Date getWorkOrderDate() {
		return this.workOrderDate;
	}

	public void setWorkOrderDate(java.util.Date workOrderDate) {
		this.workOrderDate = workOrderDate;
	}

	public java.util.Date getInspectionCheckDate() {
		return this.inspectionCheckDate;
	}

	public void setInspectionCheckDate(java.util.Date inspectionCheckDate) {
		this.inspectionCheckDate = inspectionCheckDate;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.util.Date getArchiveDate() {
		return this.archiveDate;
	}

	public void setArchiveDate(java.util.Date archiveDate) {
		this.archiveDate = archiveDate;
	}

	public java.lang.String getItgMonthlyPlanId() {
		return this.itgMonthlyPlanId;
	}

	public void setItgMonthlyPlanId(java.lang.String itgMonthlyPlanId) {
		this.itgMonthlyPlanId = itgMonthlyPlanId;
	}

	public java.lang.String getInspectionWorkOrderReasonId() {
		return this.inspectionWorkOrderReasonId;
	}

	public void setInspectionWorkOrderReasonId(
			java.lang.String inspectionWorkOrderReasonId) {
		this.inspectionWorkOrderReasonId = inspectionWorkOrderReasonId;
	}

	public java.util.List<com.myspace.surveillanceproject.Documents> getDocuments() {
		return this.documents;
	}

	public void setDocuments(
			java.util.List<com.myspace.surveillanceproject.Documents> documents) {
		this.documents = documents;
	}

	public java.util.List<java.lang.String> getInstitutionList() {
		return this.institutionList;
	}

	public void setInstitutionList(
			java.util.List<java.lang.String> institutionList) {
		this.institutionList = institutionList;
	}

	public java.lang.String getComplexityFactor() {
		return this.complexityFactor;
	}

	public void setComplexityFactor(java.lang.String complexityFactor) {
		this.complexityFactor = complexityFactor;
	}

	public InspectionWorkOrder(
			java.util.Date workOrderDate,
			java.util.Date inspectionCheckDate,
			java.lang.String archiveNumber,
			java.lang.String inspectionScope,
			java.util.List<com.myspace.surveillanceproject.LawInstance> laws,
			com.myspace.surveillanceproject.CommonInspectionObject common,
			java.lang.String id,
			java.lang.String type,
			java.util.Date archiveDate,
			java.lang.String itgMonthlyPlanId,
			java.lang.String inspectionWorkOrderReasonId,
			java.util.List<com.myspace.surveillanceproject.Documents> documents,
			java.util.List<java.lang.String> institutionList,
			java.lang.String complexityFactor) {
		this.workOrderDate = workOrderDate;
		this.inspectionCheckDate = inspectionCheckDate;
		this.archiveNumber = archiveNumber;
		this.inspectionScope = inspectionScope;
		this.laws = laws;
		this.common = common;
		this.id = id;
		this.type = type;
		this.archiveDate = archiveDate;
		this.itgMonthlyPlanId = itgMonthlyPlanId;
		this.inspectionWorkOrderReasonId = inspectionWorkOrderReasonId;
		this.documents = documents;
		this.institutionList = institutionList;
		this.complexityFactor = complexityFactor;
	}

}