package com.myspace.surveillanceproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InspectionSubject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("address")
	private java.lang.String address;
	@org.kie.api.definition.type.Label("phoneNumber")
	private java.lang.String phoneNumber;
	@org.kie.api.definition.type.Label("email")
	private java.lang.String email;
	@org.kie.api.definition.type.Label("bankAccount")
	private java.lang.String bankAccount;
	@org.kie.api.definition.type.Label("bankAccountNumber")
	private java.lang.String bankAccountNumber;

	@org.kie.api.definition.type.Label(value = "companyRegistrationNumber")
	private java.lang.String companyRegistrationNumber;

	@org.kie.api.definition.type.Label(value = "taxNumber")
	private java.lang.String taxNumber;

	public InspectionSubject() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(java.lang.String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getBankAccount() {
		return this.bankAccount;
	}

	public void setBankAccount(java.lang.String bankAccount) {
		this.bankAccount = bankAccount;
	}

	public java.lang.String getBankAccountNumber() {
		return this.bankAccountNumber;
	}

	public void setBankAccountNumber(java.lang.String bankAccountNumber) {
		this.bankAccountNumber = bankAccountNumber;
	}

	public java.lang.String getCompanyRegistrationNumber() {
		return this.companyRegistrationNumber;
	}

	public void setCompanyRegistrationNumber(
			java.lang.String companyRegistrationNumber) {
		this.companyRegistrationNumber = companyRegistrationNumber;
	}

	public java.lang.String getTaxNumber() {
		return this.taxNumber;
	}

	public void setTaxNumber(java.lang.String taxNumber) {
		this.taxNumber = taxNumber;
	}

	public InspectionSubject(java.lang.String name, java.lang.String address,
			java.lang.String phoneNumber, java.lang.String email,
			java.lang.String bankAccount, java.lang.String bankAccountNumber,
			java.lang.String companyRegistrationNumber,
			java.lang.String taxNumber) {
		this.name = name;
		this.address = address;
		this.phoneNumber = phoneNumber;
		this.email = email;
		this.bankAccount = bankAccount;
		this.bankAccountNumber = bankAccountNumber;
		this.companyRegistrationNumber = companyRegistrationNumber;
		this.taxNumber = taxNumber;
	}

}