package com.myspace.surveillanceproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LawInstance implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "article")
	private java.lang.String article;
	@org.kie.api.definition.type.Label(value = "paragraph")
	private java.lang.String paragraph;
	@org.kie.api.definition.type.Label(value = "item")
	private java.lang.String item;
	@org.kie.api.definition.type.Label(value = "law")
	private java.lang.String law;

	public LawInstance() {
	}

	public java.lang.String getArticle() {
		return this.article;
	}

	public void setArticle(java.lang.String article) {
		this.article = article;
	}

	public java.lang.String getParagraph() {
		return this.paragraph;
	}

	public void setParagraph(java.lang.String paragraph) {
		this.paragraph = paragraph;
	}

	public java.lang.String getItem() {
		return this.item;
	}

	public void setItem(java.lang.String item) {
		this.item = item;
	}

	public java.lang.String getLaw() {
		return this.law;
	}

	public void setLaw(java.lang.String law) {
		this.law = law;
	}

	public LawInstance(java.lang.String article, java.lang.String paragraph,
			java.lang.String item, java.lang.String law) {
		this.article = article;
		this.paragraph = paragraph;
		this.item = item;
		this.law = law;
	}

}