package com.myspace.surveillanceproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PersonPresent implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "fullName")
	private java.lang.String fullName;
	@org.kie.api.definition.type.Label(value = "role")
	private java.lang.String role;

	public PersonPresent() {
	}

	public java.lang.String getFullName() {
		return this.fullName;
	}

	public void setFullName(java.lang.String fullName) {
		this.fullName = fullName;
	}

	public java.lang.String getRole() {
		return this.role;
	}

	public void setRole(java.lang.String role) {
		this.role = role;
	}

	public PersonPresent(java.lang.String fullName, java.lang.String role) {
		this.fullName = fullName;
		this.role = role;
	}

}