package com.myspace.surveillanceproject;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Repercussion implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("description")
	private java.lang.String description;
	@org.kie.api.definition.type.Label("date")
	private Date date;

	@org.kie.api.definition.type.Label("measureType")
	private java.lang.String measureType;

	@org.kie.api.definition.type.Label(value = "inspectionMeasureDueDays")
	private java.lang.Integer inspectionMeasureDueDays;

	public Repercussion() {
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.util.Date getDate() {
		return this.date;
	}

	public void setDate(java.util.Date date) {
		this.date = date;
	}

	public java.lang.String getMeasureType() {
		return this.measureType;
	}

	public void setMeasureType(java.lang.String measureType) {
		this.measureType = measureType;
	}

	public java.lang.Integer getInspectionMeasureDueDays() {
		return this.inspectionMeasureDueDays;
	}

	public void setInspectionMeasureDueDays(
			java.lang.Integer inspectionMeasureDueDays) {
		this.inspectionMeasureDueDays = inspectionMeasureDueDays;
	}

	public Repercussion(java.lang.String description, java.util.Date date,
			java.lang.String measureType,
			java.lang.Integer inspectionMeasureDueDays) {
		this.description = description;
		this.date = date;
		this.measureType = measureType;
		this.inspectionMeasureDueDays = inspectionMeasureDueDays;
	}

}